# Generated by Django 3.2.13 on 2022-06-02 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productgallery',
            old_name='image',
            new_name='images',
        ),
    ]
