# Generated by Django 3.2.13 on 2022-06-02 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_image_productgallery_images'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductGallery',
        ),
    ]
